version: 0.2

phases:
  pre_build:
    commands:
      - echo $ECR
      - echo $ECR:latest
      - echo Logando no Docker Hub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      - echo Logando no Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR
  build:
    commands:
      - echo Build iniciado em `date`
      - echo Building a imagem Docker...
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:latest $ECR:latest
  post_build:
    commands:
      - echo Build completo em `date`
      - echo Pushing thea imagem Docker...
      - docker push $ECR:latest
      - printf '[{"name":$IMAGE_NAME,"imageUri":$ECR:latest}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
