version: 0.2

phases:
  pre_build:
    commands:
      - echo Logando no Docker Hub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      - echo Logando no Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR
  build:
    commands:
      - echo Build iniciado em `date`
      - echo Building a imagem Docker...
      - docker build -t fvmr-node-app .
      - docker tag fvmr-node-app:latest $ECR_URI
  post_build:
    commands:
      - echo Build completo em `date`
      - echo Pushing thea imagem Docker...
      - docker push $ECR_URI
      - printf '[{"name":"fvmr-node-app-container","imageUri":"170192930815.dkr.ecr.us-east-1.amazonaws.com/fvmr-node-app:latest"}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
