version: "3.3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecobe-frontend
    container_name: ecobe-frontend
    # volumes:
    #   - $PWD/.:/home/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
